name: safecom_final
description: "SafeCom Emergency Reporting System."

# The following line prevents the package from being accidentally published to
publish_to: 'none'


# Flutter version
version: 1.0.0+1



environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter


# Cupertino Icons  # For iOS design language
  cupertino_icons: ^1.0.8

## Local Storage
  shared_preferences: ^2.2.2

## Image Picker
  image_picker: ^1.0.4

##bloc
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  bloc: ^8.1.3

## Dependency Injection
  get_it: ^7.6.4  ## HTTP and Location
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  path: ^1.8.3

## firebase
  


##notifications
  firebase_messaging: ^14.4.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5
  google_sign_in: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter_icons:
  android: true
  ios: true
  image_path: "Images/logo.png"


# Flutter package 
flutter:
  uses-material-design: true

##assets
  assets:
    - Images/
