name: safecom_final
description: "SafeCom Emergency Reporting System."


publish_to: 'none'



version: 1.0.0+1



environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

##bloc
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  bloc: ^8.1.3

## firebase
  firebase_core: ^2.16.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^4.10.0
  firebase_storage: ^11.1.0


##notifications
  firebase_messaging: ^14.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter_icons:
  android: true
  ios: true
  image_path: "Images/logo.png"



flutter:
  uses-material-design: true

##assets
  assets:
    - Images/
